# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/coding',
                'doc_host': 'https://mohammed8079.github.io',
                'git_url': 'https://github.com/mohammed8079/coding',
                'lib_path': 'coding'},
  'syms': {'coding.core': {'coding.core.foo': ('core.html#foo', 'coding/core.py')}}}
